HEFENG_HOST1: "a"  # 替换为你的和风天气API主机地址1
HEFENG_HOST2: "b"  # 替换为你的和风天气API主机地址2
HEFENG_KEY1: "APIKEY1" # 替换为你的和风天气API密钥1
HEFENG_KEY2: "APIKEY2" # 替换为你的和风天气API密钥2
times: 120 #请求频率，单位为秒
TURNSTILE_SECRET_KEY: "0x"  # 替换为你的 Cloudflare Turnstile Secret Key
TURNSTILE_SITE_KEY: "" # 替换成你自己的 Site Key
LOCATION_NAME: "广州"  # 替换为服务器所在地，用于前端展示
LOCATION_ID: 101280101  # 广东广州的和风天气位置ID
# 管理员配置
admin_username: techccy
admin_password: ""
force_rain_duration: 10   # 强制降雨持续时间（分钟）
totp_decrypt_password: "password"
