HEFENG_HOST1: "a"  # 替换为你的和风天气API主机地址1，设计为两个轮换使用，若只有一个可以填相同的
HEFENG_HOST2: "b"  # 替换为你的和风天气API主机地址2
HEFENG_KEY1: "APIKEY1" # 替换为你的和风天气API密钥1，设计为两个轮换使用，若只有一个可以填相同的
HEFENG_KEY2: "APIKEY2" # 替换为你的和风天气API密钥2
times: 60 # 请求频率，单位为秒，和风天气免费API额度每分钟请求一次刚刚好
TURNSTILE_SECRET_KEY: "0x"  # 替换为你的 Cloudflare Turnstile Secret Key
TURNSTILE_SITE_KEY: "0x" # 替换成你自己的 Site Key
LOCATION_NAME: "广州"  # 替换为服务器所在地，用于前端展示
LOCATION_ID: 101280101  # 广东广州的和风天气位置ID
admin_username: techccy # 管理员登录账号
admin_password: "" # 管理员登录密码
force_rain_duration: 10   # 强制降雨持续时间（分钟）
totp_decrypt_password: "password" #用于加密管理员登录时二次验证器密钥的密码