API_KEY: "***"
times: 3 #3分钟一次
TURNSTILE_SECRET_KEY: "***"  # 替换为你的 Cloudflare Turnstile Secret Key
TURNSTILE_SITE_KEY: "***" # 替换成你自己的 Site Key
# 管理员配置
admin_username: "***"
admin_password: "***"
force_rain_duration: 10   # 强制降雨持续时间（分钟）
